# Generated by Django 4.1.7 on 2023-03-02 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 14, 8, 19, 135966, tzinfo=datetime.timezone.utc)),
        ),
    ]
