# Generated by Django 4.1.7 on 2023-02-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='Processor',
            new_name='processor',
        ),
    ]
